name: chemsmart
channels:
  - conda-forge  # handles conda installations
  - defaults
dependencies:
  - python=3.10
  - xtb
  - pymol-open-source=3.1.0
  - ffmpeg=7.1.1  # movie support for pymol
  - openbabel          # includes Python bindings on conda-forge
  - pip
  - pip:
      - -e .[dev,test,docs]   # pulls all Python deps from pyproject.toml
